### ISSUE TITLE
Parsing x509 cert extensions

### ISSUE THREAD

**Issue by robert-kisteleki** [RIPE-NCC/ripe.atlas.sagan#80]
In order to support checks on subject name, one needs to dig into certificate extensions, namely subject alternative name (SAN). Sagan at the moment does not expose certificate extensions to the client.

It seems there are multiple ways going about this.

1. pyopenssl, which the library currently uses, can [enumerate](https://pyopenssl.readthedocs.io/en/latest/api/crypto.html#OpenSSL.crypto.X509.get_extension) [extensions](https://pyopenssl.readthedocs.io/en/latest/api/crypto.html#x509extension-objects), but it does not parse them, only gives an asn1 blob back. There's an undocumented function named _subjectAltNameString which works, but it's unclear if one can rely on it.

2. Use the python cryptography module (suggested by @chrisamin) which seems simpler, but it also means either parsing certs twice or replacing current pyopenssl code with it.

Opinions?

**Comment by danielquinn** [comment]
If `cryptography` supports everything that pyopenssl does, I'd say switch completely as it's well-supported module.  I've used both and prefer the former.

**Comment by astrikos** [comment]
this is fixed by #81 right?

**Comment by robert-kisteleki** [comment]
Yes, that was the point of #81
